<?php

namespace OC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
    public function getAdvertWithCategories(array $categoryNames)
    {
        //Jointure avec l'entité Category
        $qb = $this
            ->createQueryBuilder('a')
            ->join('a.categories', 'c')
            ->addSelect('c');

        //Filtre avec les noms du tableau de catégories passés en paramètres
        $qb->where($qb->expr()->in('c.name', $categoryNames));

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function getApplicationsWithAdvert($limit)
    {
        $qb = $this->createQueryBuilder('a');

        // Jointure avec l'entité Advert
        $qb
            ->join('a.advert', 'adv')
            ->addSelect('adv')
        ;

        //On impose la limite
        $qb->setMaxResults($limit);

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
